export const COLOR_LIST_REQUEST = 'COLOR_LIST_REQUEST'
export const COLOR_LIST_SUCCESS = 'COLOR_LIST_SUCCESS'
export const COLOR_LIST_FAIL = 'COLOR_LIST_FAIL'

export const COLOR_CREATE_REQUEST = 'COLOR_CREATE_REQUEST'
export const COLOR_CREATE_SUCCESS = 'COLOR_CREATE_SUCCESS'
export const COLOR_CREATE_FAIL = 'COLOR_CREATE_FAIL'
export const COLOR_CREATE_DEFAULT = 'COLOR_CREATE_DEFAULT'

export const COLOR_DELETE_REQUEST = 'COLOR_DELETE_REQUEST'
export const COLOR_DELETE_SUCCESS = 'COLOR_DELETE_SUCCESS'
export const COLOR_DELETE_FAIL = 'COLOR_DELETE_FAIL'

export const COLOR_DETAIL_REQUEST = 'COLOR_DETAIL_REQUEST'
export const COLOR_DETAIL_SUCCESS = 'COLOR_DETAIL_SUCCESS'
export const COLOR_DETAIL_FAIL = 'COLOR_DETAIL_FAIL'
export const COLOR_DETAIL_DEFAULT = 'COLOR_DETAIL_DEFAULT'

export const COLOR_UPDATE_REQUEST = 'COLOR_UPDATE_REQUEST'
export const COLOR_UPDATE_SUCCESS = 'COLOR_UPDATE_SUCCESS'
export const COLOR_UPDATE_FAIL = 'COLOR_UPDATE_FAIL'
export const COLOR_UPDATE_DEFAULT = 'COLOR_UPDATE_DEFAULT'