export const INVENTORY_ADD_REQUSET = 'INVENTORY_ADD_REQUEST'
export const INVENTORY_ADD_SUCCESS = 'INVENTORY_ADD_SUCCESS'
export const INVENTORY_ADD_FAIL = 'INVENTORY_ADD_FAIL'
export const INVENTORY_ADD_DEFAULT = 'INVENTORY_ADD_DEFAULT'

export const INVENTORY_DELETE_REQUSET = 'INVENTORY_DELETE_REQUEST'
export const INVENTORY_DELETE_SUCCESS = 'INVENTORY_DELETE_SUCCESS'
export const INVENTORY_DELETE_FAIL = 'INVENTORY_DELETE_FAIL'
export const INVENTORY_DELETE_DEFAULT = 'INVENTORY_DELETE_DEFAULT'

export const INVENTORY_UPDATE_REQUSET = 'INVENTORY_UPDATE_REQUEST'
export const INVENTORY_UPDATE_SUCCESS = 'INVENTORY_UPDATE_SUCCESS'
export const INVENTORY_UPDATE_FAIL = 'INVENTORY_UPDATE_FAIL'
export const INVENTORY_UPDATE_DEFAULT = 'INVENTORY_UPDATE_DEFAULT'