export const INVENTORY_ADD_REQUSET = 'INVENTORY_ADD_REQUEST'
export const INVENTORY_ADD_SUCCESS = 'INVENTORY_ADD_SUCCESS'
export const INVENTORY_ADD_FAIL = 'INVENTORY_ADD_FAIL'
export const INVENTORY_ADD_DEFAULT = 'INVENTORY_ADD_DEFAULT'