export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'
export const PRODUCT_DETAIL_CLEAR = 'PRODUCT_DETAIL_CLEAR'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_DEFAULT = 'PRODUCT_CREATE_DEFAULT'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_DEFAULT = 'PRODUCT_UPDATE_DEFAULT'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_DEFAULT = 'PRODUCT_CREATE_REVIEW_DEFAULT'

export const PRODUCT_DELETE_REVIEW_REQUEST = 'PRODUCT_DELETE_REVIEW_REQUEST'
export const PRODUCT_DELETE_REVIEW_SUCCESS = 'PRODUCT_DELETE_REVIEW_SUCCESS'
export const PRODUCT_DELETE_REVIEW_FAIL = 'PRODUCT_DELETE_REVIEW_FAIL'
export const PRODUCT_DELETE_REVIEW_DEFAULT = 'PRODUCT_DELETE_REVIEW_DEFAULT'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_INVENTORY_REQUEST = 'PRODUCT_INVENTORY_REQUEST'
export const PRODUCT_INVENTORY_SUCCESS = 'PRODUCT_INVENTORY_SUCCESS'
export const PRODUCT_INVENTORY_FAIL = 'PRODUCT_INVENTORY_FAIL'
export const PRODUCT_INVENTORY_DEFAULT = 'PRODUCT_INVENTORY_DEFAULT'

export const PRODUCT_SHOPNOW_REQUEST = 'PRODUCT_SHOPNOW_REQUEST'
export const PRODUCT_SHOPNOW_SUCCESS = 'PRODUCT_SHOPNOW_SUCCESS'
export const PRODUCT_SHOPNOW_FAIL = 'PRODUCT_SHOPNOW_FAIL'
export const PRODUCT_SHOPNOW_DEFAULT = 'PRODUCT_SHOPNOW_DEFAULT'